/* SPDX-License-Identifier: GPL-2.0-or-later */

/* TEXTURE SLOTS */
#define WB_MATCAP_SLOT 0
#define WB_TEXTURE_SLOT 1
#define WB_TILE_ARRAY_SLOT 2
#define WB_TILE_DATA_SLOT 3
/* UBO SLOTS */
#define WB_WORLD_SLOT 4
/* SSBO SLOTS */
#define WB_MATERIAL_SLOT 0
#define WB_MATERIAL_START_SLOT 1

#define WB_RESOLVE_GROUP_SIZE 8
