# SPDX-FileCopyrightText: 2024 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

set(CCCL_EXTRA_ARGS
  -DCCCL_ENABLE_LIBCUDACXX=ON
  -DCCCL_ENABLE_CUB=OFF
  -DCCCL_ENABLE_THRUST=ON
  -DCCCL_ENABLE_TESTING=OFF
  -DCCCL_ENABLE_EXAMPLES=OFF
  -DCCCL_ENABLE_BENCHMARKS=OFF
  -DTHRUST_CPP_DIALECT=17
  -DTHRUST_ENABLE_MULTICONFIG=ON
  -DTHRUST_MULTICONFIG_ENABLE_SYSTEM_CUDA=OFF
  -DTHRUST_MULTICONFIG_ENABLE_SYSTEM_CPP=ON
  -DTHRUST_MULTICONFIG_ENABLE_SYSTEM_TBB=ON
  -DTHRUST_MULTICONFIG_ENABLE_SYSTEM_OMP=OFF
  -DTHRUST_MULTICONFIG_ENABLE_DIALECT_ALL=OFF
  -DTHRUST_MULTICONFIG_ENABLE_DIALECT_CPP11=OFF
  -DTHRUST_MULTICONFIG_ENABLE_DIALECT_CPP14=OFF
  -DTHRUST_MULTICONFIG_ENABLE_DIALECT_CPP17=ON
  -DTHRUST_MULTICONFIG_ENABLE_DIALECT_CPP20=OFF
  -DTHRUST_HOST_SYSTEM=CPP
  -DTHRUST_DEVICE_SYSTEM=TBB
  -DTHRUST_TBB_ROOT=${LIBDIR}/tbb/
  -DTHRUST_ENABLE_HEADER_TESTING=OFF
  -DTHRUST_ENABLE_EXAMPLES=OFF
  -DTHRUST_ENABLE_TESTING=OFF
  -DLIBCUDACXX_ENABLE_LIBCUDACXX_TESTS=OFF
)

ExternalProject_Add(external_cccl
  URL file://${PACKAGE_DIR}/${CCCL_FILE}
  DOWNLOAD_DIR ${DOWNLOAD_DIR}
  URL_HASH ${CCCL_HASH_TYPE}=${CCCL_HASH}
  PREFIX ${BUILD_DIR}/cccl
  CMAKE_GENERATOR ${PLATFORM_ALT_GENERATOR}

  PATCH_COMMAND
    ${PATCH_CMD} -p 1 -N -d
      ${BUILD_DIR}/cccl/src/external_cccl/ <
      ${PATCH_DIR}/cccl.diff

  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${LIBDIR}/cccl
    ${DEFAULT_CMAKE_FLAGS}
    ${CCCL_EXTRA_ARGS}

  INSTALL_DIR ${LIBDIR}/cccl
)
